files:
  - source: /lang/en.json
    translation: /lang/%two_letters_code%.json
  - source: /static/**/*.html
    ignore:
      - '*.test.html'
      - '*.??.html'
    translation: /%original_path%/%file_name%.%two_letters_code%.html
commit_message: 'i18n(%language%): update %original_file_name%'
append_commit_message: false
